pocket_fetch:
  cron: "*/5 * * * *"
  queue: cron
  class: CronTask
  args: "pocket_fetch"
  description: Fetches Updates from pocket
twitter_fetch:
  cron: "*/5 * * * *"
  queue: cron
  class: CronTask
  args: "twitter_fetch"
  description: Fetches Updates from twitter