# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  admin_name: First User
  admin_email: user@example.com
  admin_password: changeme
  domain_name: clipx.in
  secret_key_base: 3ba0003d503dac7f83503a8b59671699302fcc89f75c4da68b673fea923398b20fefe1cf3665541cafe5108b257ba7e5111f999543933b8e93c8e0c7bb2c8064
  pocket_key: 29715-eed568b5ba0d1e7d735a1658
  readability_parser_key: 28a84b516f114f65b04997778fecc73a6a6876a4
  evernote_key: captn3m0-5624
  evernote_secret: bd7e1878b9f43123

test:
  domain_name: example.com 
  secret_key_base: fcb48bb77214cd391d8bd8511b633ad19c637d9d222d3539682599e0e1c9550f721a06e8fee151bff71885a8ddbacf3c3ba9b4ebbcd850ac373a9afd97c88672

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  admin_name: <%= ENV["ADMIN_NAME"] %>
  admin_email: <%= ENV["ADMIN_EMAIL"] %>
  admin_password: <%= ENV["ADMIN_PASSWORD"] %>
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  pocket_key: <%= ENV["POCKET_KEY"] %>
  readability_parser_key: <%= ENV["READABILITY_PARSER_KEY"] %>